#server
server:
  port: 8788 
  context-path: /file
  


#mongodb config
spring:
  data:
    mongodb: 
      host: 192.168.22.209
      port: 27017
      database: cloudWork
      grid-fs-database: bulletinFile

  cache:
    ehcache:
      config: classpath:config/ehcache.xml 
  http:
    multipart:
      max-file-size: 20Mb 
      max-request-size: 20Mb



#loging
logging: 
  config: classpath:config/logback-spring.xml
